nginx:
    build: ./config
    ports:
        - "80:80"
        - "443:443"
    volumes_from:
      - php
    links:
      - php
php:
    build: ./config/php
    ports:
        - "9000:9000"
    tty: true
    volumes:
      - ./:/var/www/kliusasproject
    links:
      - mysql
      - redis
    working_dir: /var/www/kliusasproject/database
mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kliusasproject
      - MYSQL_USER=kliusasproject
      - MYSQL_PASSWORD=kliusasproject
redis:
    image: redis
    ports:
      - "6379:6379"
composer:
  restart: 'no'
  image: composer/composer:php7
  command: install --ignore-platform-reqs --no-scripts
  volumes:
    - .:/app